# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr:
  - 1.0-dev
  - fasttrack*
  - main

# pool: mariner-core-x64-1es-mariner2-gpt-test

resources:
  repositories:
  - repository: CBL-Mariner-Pipelines
    type: git
    name: mariner/CBL-Mariner-Pipelines

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- template: .pipelines/templates/KernelModulesSigning.yml@CBL-Mariner-Pipelines
  parameters:
    artifactsFolder: '$(Build.ArtifactStagingDirectory)/$(buildArtifactsFolder)'
    repoRootPath: '$(Agent.BuildDirectory)/CBL-Mariner-Pipelines'

# - script: |
#       exit 1
#   displayName: 'Fail'
